const allTexts = [
    {
        en: `Tell me, Muse, about the cunning man who wandered so far, after Troy destroyed the holy citadel. Many were the peoples whose cities he observed, whose spirits met and were many at sea the sufferings he went through to save his life, to get the companions back to their homes.`,
        pt: `Fala-me, Musa, do homem astuto que tanto vagueou, depois que de Troia destruiu a cidadela sagrada. Muitos foram os povos cujas cidades observou, cujos espíritos conheceu e foram muitos no mar os sofrimentos por que passou para salvar a vida, para conseguir o retorno dos companheiros a suas casas.`,
        en_id: 1 
    },
    {
        en: `In ancient Rome, there was the habit of celebrating the birthday of a person. There weren’t parties like we know today, but cakes were prepared and offers were made. Then, the habits of wishing happy birthday, giving gifts and lighting candles became popular as a way to protect the birthday person from devils and ensure good things to the next year in the person’s life. The celebrations only became popular like we know today after fourteen centuries, in a collective festival performed in Germany.`,
        pt: `Na Roma antiga, havia o costume de comemorar o aniversário de uma pessoa. Não havia festas como a que conhecemos hoje, mas preparavam-se bolos e faziam-se ofertas. Então, os hábitos de desejar feliz aniversário, dar presentes e acender velas se popularizaram como forma de proteger o aniversariante dos demônios e garantir coisas boas para o próximo ano na vida da pessoa. As comemorações só se popularizaram como conhecemos hoje depois de quatorze séculos, em um festival coletivo realizado na Alemanha.`,
        en_id: 2 
    },
    {
        en: `Since 1960, the Hollywood Boulevard Avenue attracts visitors to see star-plaques with the names of celebrities: actors, singers, movie directors, stage performers or anyone who has contributed to make Hollywood known worldwide. Each pink star is made of a marble called terrazzo, a bronze shield with the honoree’s name and an icon of the celebrity job, like a camera, television or a microphone, for example.`,
        pt: `Desde 1960, a Hollywood Boulevard Avenue atrai visitantes para ver placas de estrelas com nomes de celebridades: atores, cantores, diretores de cinema, artistas de palco ou qualquer pessoa que tenha contribuído para tornar Hollywood conhecida mundialmente. Cada estrela rosa é feita de um mármore chamado terrazzo, um escudo de bronze com o nome do homenageado e um ícone do trabalho da celebridade, como uma câmera, televisão ou microfone, por exemplo.`,
        en_id: 3
    },
    {
        en: `One morning, my mother woke me up and told me that my Aunt Zeny and her children were downstairs. They came to invite us for a swim at the beach. The beach is just an hour away from our place, so my mom decided to go with them. My mom helped me prepare my bag. We did not cook any food since we would buy snacks on the way. I could see my cousins’ excitement as we headed towards the beach. I was excited, too. However, I am afraid of the water and can’t swim. All of my cousins hurriedly went to the shore as we arrived. I panicked a little, but I saw my mother staring at me. She was smiling at me. It was like she was telling me to, “Go ahead son, and learn to swim.”`,
        pt: `Certa manhã, minha mãe me acordou e me disse que minha tia Zeny e seus filhos estavam lá embaixo. Eles vieram para nos convidar para um mergulho na praia. A praia fica a apenas uma hora de distância da nossa casa, por isso a minha mãe decidiu ir com eles. Minha mãe me ajudou a preparar a minha mala. Nós não cozinhamos qualquer comida uma vez que compraríamos lanches no caminho. Eu podia ver a excitação de meus primos enquanto nos dirigíamos para a praia. Eu estava animado, também. No entanto, tenho medo da água e não consigo nadar. Todos os meus primos apressadamente foram para a margem quando chegamos. Entrei em pânico um pouco, mas vi minha mãe me encarando. Ela estava sorrindo para mim. Era como se ela estivesse me dizendo: “Vá em frente filho, e aprender a nadar.”`,
        en_id: 4
    },
    {
        en: `Luke is the team leader of the school project. He’s smart but bossy. He has ideas but doesn’t welcome other people’s views. He wants to always take charge. He does ask for members’ thoughts but never approves anything. He doesn’t seem to like any idea at all. His expression is always “I don’t like that idea. I don’t think that will work.” One day, all the members excluded him from a discussion. They thought about the best way to solve the problem of Luke. Nash suggested refining their proposals. Joe insisted to just let Luke do everything by himself. Eric recommended replacing the appointed leader. However, none of the suggestions seemed right. Then, the quietest member spoke. “Let’s just stick together and let Luke find other members he would 100% approve.” Everybody exclaimed, “he likes that idea”.`,
        pt: `Luke é o líder da equipe do trabalho da escola. Ele é esperto, mas mandão. Ele tem ideias, mas não dá boas-vindas às opiniões de outras pessoas. Ele quer sempre tomar conta. Ele pede os pensamentos dos membros, mas nunca aprova nada. Ele não parece gostar de ideia alguma. Sua expressão é sempre “Eu não gosto dessa idéia. Eu não acho que isso vai funcionar. “Um dia, todos os membros o excluíram de uma discussão. Eles pensaram sobre a melhor maneira de resolver o problema de Luke. Nash sugeriu refinar suas propostas. Joe insistiu para deixar Luke fazer tudo sozinho. Eric recomendou a substituição do líder designado. No entanto, nenhuma das sugestões parecia a certa. Então, o membro mais silencioso falou. “Vamos ficar juntos e deixar Luke encontrar outros membros que ele iria aprovar 100%.” Todo mundo exclamou, “ele gosta dessa idéia”.`,
        en_id: 5
    },
    {
        en: `One sunny day, JM and MJ were playing marbles outside their house which was near the busy streets. Accidentally, JM had dropped his marbles. It went down the street where many cars were passing by. This was very dangerous, but they attempted to get the marble anyway. A man in a uniform approached the two boys. He was acting in an authoritative manner. The boys were startled and were about to cry. Their mother overheard them and went outside, angry with the man. However, he turned out to be a chief police officer. He explained what happened and the boys’ mother started to worry and felt sorry about not looking after her children. The chief warned the boys to not play in the streets again. The boys learned a lesson and didn’t play outside anymore.`,
        pt: `Um dia ensolarado, JM e MJ estavam jogando bolinhas de gude fora da sua casa que era perto das ruas movimentadas. Acidentalmente, JM havia deixado cair as bolinhas. Ele desceu a rua onde muitos carros estavam passando. Isto era muito perigoso, mas eles tentaram pegar as bolinhas de gude de qualquer maneira. Um homem de uniforme aproximou-se dos dois meninos. Ele estava agindo de forma autoritária. Os garotos ficaram surpresos e estavam prestes a chorar. A mãe os ouviu e saiu, zangada com o homem. No entanto, ele acabava por ser um chefe de polícia. Ele explicou o que aconteceu e a mãe dos meninos começou a se preocupar e sentiu pena por não cuidar de seus filhos. O chefe advertiu os meninos para não jogar nas ruas novamente. Os rapazes aprenderam uma lição e não brincaram fora mais.`,
        en_id: 6
    },
    {
        en: `Sam and Stuart are both thrill seekers. They decided to explore this new island located near the Pacific called Ravi. They packed their bags and took off from their homes. They both thought that this would be a great adventure for them. They rode a boat going to the island. The sun was up, but the wind was strong. There were strong waves. The boat almost overturned. However, they arrived at the island safe. Then, they realized the bag holding their food and water was gone. They probably dropped it during the boat trip. Sam asked, “How will we be able to survive our trip with no food and no water?” Stuart simply answered him, “We’ll find a way.” Sam added, “How come you are not panicking about this?” Stuart responded, “Well, this is the real adventure.”`,
        pt: `Sam e Stuart são ambos buscadores de emoção. Eles decidiram explorar esta nova ilha localizada perto do Pacífico chamada Ravi. Eles empacotaram suas malas e saíram de suas casas. Ambos pensaram que esta seria uma grande aventura para eles. Eles montaram um barco indo para a ilha. O sol estava acima, mas o vento era forte. Havia ondas fortes. O barco quase virou. No entanto, eles chegaram à ilha a salvo. Então, eles perceberam que a sacola carregando a comida e a água tinha desaparecido. Provavelmente caíram durante a viagem de barco. Sam perguntou: “Como vamos ser capazes de sobreviver a nossa viagem sem comida e sem água?” Stuart simplesmente respondeu: “Encontraremos um caminho.” Sam acrescentou: “Como é que você não está em pânico com isso?” Stuart Respondeu: “Bem, esta é a verdadeira aventura.”`,
        en_id: 7
    },
    {
        en: `Josh and Joy couldn’t be more different from each other. Josh is chic and his hair is always sleek. He likes to sleep in class, and play in gym class. He excels in sports which is probably why he’s the basketball captain. On the other hand, Joy can’t care less about her looks. Her straight hair sometimes covers her face. She doesn’t wear makeup like her female classmates, either. While Joy almost always fails P.E., she excels in other subjects. Joy loves studying. Josh and Joy can always be seen together. People wonder what Josh sees in Joy. She doesn’t seem to fit him. One day, his friend finally asks him, “Do you love Joy? What do you even see in her?” To him, Josh replies angrily, “Why shouldn’t I love my twin sister?”`,
        pt: `Josh e Joy não podiam ser mais diferentes uns dos outros. Josh é elegante e seu cabelo é sempre elegante. Ele gosta de dormir em sala de aula e jogar na aula de educação fisica. Ele se destaca em esportes que é provavelmente o porquê dele ser o capitão de basquete. Por outro lado, Joy não pode se importar menos com sua aparência. Seus cabelos lisos às vezes cobrem seu rosto. Ela não usa maquiagem como suas colegas de classe, também. Enquanto Joy quase sempre reprova em educação fisica, ela se destaca em outros assuntos. Joy gosta de estudar. Josh e Joy podem ser vistos juntos. As pessoas se perguntam o que Josh vê na Joy. Ela não parece se encaixar com ele. Um dia, seu amigo finalmente pergunta: “Você ama a joy? O que você vê nela? “Para ele, Josh responde com raiva,” Por que eu não deveria amar minha irmã gêmea? “`,
        en_id: 8
    },
    {
        en: `One sunny morning, a family planned to have a picnic at the park. In order to get there, the family had to use their car. Everyone was ready and things were brought inside the vehicle. Mother had double checked everything and the rest of the family went inside the car to settle in. Unfortunately, it wouldn’t start. Everyone started to worry after dad attempted to start the engine several times. Still, it wouldn’t start. They all went out of the car and started thinking what had gotten wrong. Dad got his tools to fix it. The rest of the family members assisted him. Will the car start? Nobody knew. When everyone was about to give up, dad started the engine and the car made a familiar sound. They rejoiced as the car finally started.`,
        pt: `Uma manhã ensolarada, uma família planejou fazer um piquenique no parque. Para chegar lá, a família teve de usar o carro deles. Todo mundo estava pronto e as coisas foram trazidas para dentro do veículo. A mãe tinha verificado tudo e o resto da família entrou no carro para se instalar. Infelizmente, não daria partida. Todo mundo começou a se preocupar depois que o pai tentou ligar o motor várias vezes. Ainda assim, não daria partida. Todos saíram do carro e começaram a pensar no que havia errado. Papai tem suas ferramentas para consertá-lo. O resto dos membros da família o ajudaram. O carro dará partida? Ninguém sabia. Quando todos estavam prestes a desistir, o pai ligou o motor e o carro fez um som familiar. Eles se alegraram quando o carro finalmente deu partida.`,
        en_id: 9
    },
    {
        en: `Every school has that all-time genius. Ralph, a simple-looking kid, was that genius. Having straight As and winning every school quiz, no one can ever beat Ralph’s knowledge. Most teachers attest to the superior intelligence Ralph has displayed. Because of this, one of the teachers wants to register him in a local quiz show. When he is asked about it, Ralph exclaims, “Boy, would I!” Everyone is excited about the big quiz show. Ralph is nervous, though. He has never joined any quiz contest this big. He eventually gets himself together. Easy and difficult rounds are a breeze. The last question determines the winner. As the question is shown, Ralph’s mind goes completely blank. He knows the answer but forgets it. He closes his eyes with his hands pressed on his temples. Alas! He recalls the answer and is then announced as the winner.`,
        pt: `Toda escola tem esse gênio de todos os tempos. Ralph, um garoto de aparência simples, era aquele gênio. Sendo honesto e ganhando cada quiz escolar, ninguém pode vencer o conhecimento de Ralph. A maioria dos professores atestam a inteligência superior que Ralph demonstrou. Devido a isso, um dos professores quer registrá-lo em um concurso local. Quando ele é perguntado sobre isso, Ralph exclama, “Cara, eu iria!” Todo mundo está animado sobre o grande concurso. Ralph está nervoso, no entanto. Ele nunca se juntou a qualquer grande concurso como este. Ele finalmente se recompõe. Rodadas fáceis e difíceis são uma brisa. A última pergunta determina o vencedor. Quando a pergunta é mostrada, a mente de Ralph fica completamente em branco. Ele sabe a resposta, mas a esquece. Ele fecha os olhos com as mãos pressionadas nas têmporas. Felizmente! Ele lembra a resposta e é então anunciado como o vencedor.`,
        en_id: 10
    },
    {
        en: `Sam is 60 years old, but is still quite strong. People keep reminding him to be careful as he is no longer young. But he loves to work. He still goes to play golf, take care of his garden, clean the house in his free time, and drink with his friends once in a month. When you see him, you will think he is much younger. One day, while cleaning garden, he drops his bypass lopper. He bends down to pick it up. Suddenly, he is unable to stand back up again. He panics as it is the first time he has experienced this. Slowly, he goes inside the house and calls the doctor. Dr. Stinson says he should immediately go to the hospital. There is something wrong with his back. Sam finally realizes he’s not as young as he thinks.`,
        pt: `Sam tem 60 anos, mas ainda é bastante forte. As pessoas continuam lembrando-o de ter cuidado, já que ele não é mais jovem. Mas ele gosta de trabalhar. Ele ainda vai jogar golfe, cuidar de seu jardim, limpar a casa em seu tempo livre e beber com seus amigos uma vez ao mês. Quando você o vê, você pensará que é muito mais novo. Um dia, ao limpar o jardim, ele deixa cair seu alicate. Ele se inclina para pegá-lo. De repente, ele é incapaz de se levantar novamente. Ele entra em pânico, pois é a primeira vez que ele experimenta isso. Lentamente, ele entra na casa e chama o médico. O Dr. Stinson diz que ele deve ir imediatamente para o hospital. Há algo errado com suas costas. Sam finalmente percebe que ele não é tão jovem como ele pensa.`,
        en_id: 11
    },
    {
        en: `It was the season for festivities at the countryside of Montana. Everyone was buzzing with thrill. Homemakers joyfully prepared dishes for guests. George, a young, fit, and handsome cowboy, was there to join the town folks and to celebrate. During the festival night, George seemed to enjoy every part of it. He visited one house after another. In every home he went, hosts happily offered their hearty, delicious dishes. Feeling grateful, George gobbled up any food given to him. It was a great night. But despite this, he was completely exhausted. So, he went straight to bed after visiting the last house in town. His tummy was full, and he was well-rested. All of the sudden, he began having strange dreams. He dreamt of talking food. The most bizarre part of it was that he was the fat, naked cowboy who ate them all.`,
        pt: `Era a temporada para festividades no interior de Montana. Todo mundo estava espalhando emoção. Donas de casa alegremente preparavam pratos para os hóspedes. George, um vaqueiro jovem, apto e bonito, estava lá para juntar-se aos povos da cidade e celebrar. Durante a noite do festival, George parecia desfrutar cada parte dela. Ele visitou uma casa após a outra. Em cada casa que ele ia, os anfitriões ofereciam alegremente seus deliciosos pratos. Sentindo-se grato, George engoliu qualquer comida que lhe fosse dada. Foi uma ótima noite. Mas, apesar disso, estava completamente exausto. Então, ele foi direto para a cama depois de visitar a última casa na cidade. Sua barriga estava cheia, e ele estava bem descansado. De repente, ele começou a ter sonhos estranhos. Ele sonhou com comidas falantes. A parte mais bizarra disso era que ele era o vaqueiro gordo e nu que comia todos elas.`,
        en_id: 12
    },
    {
        en: `Lilly loves word search puzzles and is great at them. In fact, it’s the only thing she excels in. That’s what people think. Her grades at school were just enough to make her pass. Her mother would always scold her for not being good at household chores, too. Now, she has worked for a publishing company for 6 years and still hasn’t got the promotion she was promised. But that’s okay for her. She’s contented with her simple life. Nobody can understand why she has no ambition to excel in life and at work. Her friend once asked her why she lived the way she did. Lilly simply answered, “Unlike word search puzzles, I think life is pretty simple. As long as I have a bed to sleep on and food to eat, I’ll be happy.” And she is, indeed, happy.`,
        pt: `Lilly ama caça palavras e é ótima neles. Na verdade, é a única coisa que ela se destaca. É o que as pessoas pensam. Suas notas na escola eram apenas o suficiente para fazê-la passar. Sua mãe sempre a repreendia por não ser boa em tarefas domésticas, também. Agora, ela tem trabalhado para uma editora por 6 anos e ainda não tem a promoção que lhe foi prometida. Mas tudo bem para ela. Ela está contente com sua vida simples. Ninguém pode entender por que ela não tem ambição de se destacar na vida e no trabalho. Seu amigo uma vez lhe perguntou por que ela viveu do jeito que ela vivia. Lilly simplesmente respondeu, “Ao contrário de caça palavra, eu acho que a vida é muito simples. Contanto que eu tenha uma cama para dormir e comida para comer, vou ser feliz. “E ela é, de fato, feliz.`,
        en_id: 13
    },
    {
        en: `Mario was orphaned when he was seven years old. He lost his mother in childbirth, and his father was killed in an accident. Mario never knew his grandparents, aunts, and uncles. He had to strive to find food for himself. He tried washing cars for a living, but he was too short. He asked for money from passersby, but he was often pushed away. He then decided to collect cans and get money from them. Every day, Mario aimed to gather 100 cans. If he did that, he was able to earn enough money to feed him three meals a day. He strived until he was able to go to school. His teachers helped him, and he was able to get a scholarship. With perseverance and hard work, he got to build his own business. Mario is now a millionaire who started out with bags of cans.`,
        pt: `Mário ficou órfão quando tinha sete anos. Ele perdeu sua mãe no parto, e seu pai foi morto em um acidente. Mario nunca conheceu seus avós, tias e tios. Ele teve que se esforçar para encontrar comida para si mesmo. Ele tentou lavar carros para ganhar a vida, mas ele era muito pequeno. Ele pedia dinheiro aos transeuntes, mas era muitas vezes expulso. Ele então decidiu coletar latas e obter dinheiro com elas. Todos os dias, Mario pretendia juntar 100 latas. Se ele fizesse isso, ele era capaz de ganhar dinheiro suficiente para alimentá-lo três refeições por dia. Ele se esforçou até que ele foi capaz de ir para a escola. Seus professores o ajudaram, e ele conseguiu uma bolsa de estudos. Com perseverança e trabalho duro, ele conseguiu construir seu próprio negócio. Mario é agora um milionário que começou com sacos de latas.`,
        en_id: 14
    },
    {
        en: `Nelia is a superstar. She has starred in a couple of shows and numerous television series. Her fans love her, and she appreciates them. Her fans and coworkers adore her for her excellent acting skills and supreme talent. However, she is also praised for her sophistication and eye for cleanliness. She never leaves her workplace or bunker untidy. With her elevating popularity, Nelia wants to take a break. She checks into a high class hotel. The receptionist has his back turned, so she rings the bell. When the receptionist faces Nelia, he is picking his nose. Utterly disgusted, Nelia calls for the supervisor. The head receptionist arrives, and Nelia exclaims, “You teach your staff good front desk manners!” After this outburst, Nelia turns around and walks away. The receptionist is in shock. He’s a fan of Nelia.`,
        pt: `Nelia é uma super estrela. Ela estrelou um par de shows e séries de televisão numerosas. Seus fãs a amam, e ela os aprecia. Seus fãs e colegas de trabalho a adoram por suas excelentes habilidades de atuação e talento supremo. No entanto, ela também é elogiada por sua sofisticação e olho para limpeza. Ela nunca deixa seu local de trabalho ou camarim desarrumado. Com sua popularidade crescente, Nelia quer fazer uma pausa. Ela checa em um hotel de classe alta. O recepcionista está de costas viradas, então ela toca a campainha. Quando o recepcionista enfrenta Nelia, ele está cutucando o nariz. Totalmente revoltada, Nélia chama o supervisor. A recepcionista-chefe chega e Nélia exclama: “Ensine aos seus funcionários da recepção boas maneiras!” Depois dessa explosão, Nélia se vira e se afasta. O recepcionista está em choque. Ele é um fã de Nelia.`,
        en_id: 15
    },
    {
        en: `Carl graduated from their community college 4 years ago. He has an education degree and can apply to a school. However, he prefers not to. He’s currently working part-time in a convenience store. He works 4 hours in the morning. In the afternoon, he goes home to watch television and sleep. He gives all his salary to his mother. He’s still living with her. However, his salary is not enough to pay for their house and food. His mother has to work full-time as an assistant in the city library. When Carl receives an invitation to their college reunion, he declines. He says he doesn’t have money for that. His friends tell him to apply for a better job and help his mother. But Carl just says, “The economy is currently bad. I can’t get any good job.”`,
        pt: `Carl se formou em sua faculdade comunitária há 4 anos. Tem um grau de instrução e pode aplicar-se a uma escola. No entanto, ele prefere não. Ele está trabalhando atualmente em uma loja de conveniência. Ele trabalha 4 horas de manhã. À tarde, ele vai para casa para assistir televisão e dormir. Dá todo o seu salário à sua mãe. Ainda mora com ela. No entanto, seu salário não é suficiente para pagar a sua casa e comida. Sua mãe tem que trabalhar em tempo integral como assistente na biblioteca da cidade. Quando Carl recebe um convite para sua reunião de faculdade, ele declina. Ele diz que não tem dinheiro para isso. Seus amigos dizem-lhe para aplicar em um trabalho melhor e ajudar a sua mãe. Mas Carl apenas diz: “A economia está atualmente ruim. Não consigo nenhum bom trabalho.`,
        en_id: 16
    },
    {
        en: `Stephen wakes up with sweat in his face. He dreamt about flying. He hates flying. He’s 30 years old and he has never been on a plane before. He thinks his fear began when he fell from a tall tree. Luckily, he never had reason to fly before. Later that day, he goes to work. His boss calls him to the office. He’s nervous. He’s afraid he has done something wrong. He keeps thinking, but he’s sure he has met all the deadlines and has done them well. Slowly, he opens the door. The boss tells him to sit down. He has this stern look that made Stephen more afraid. Finally, his boss says, “You need to fly to Los Angeles. We have a project there that you need to manage.” The color drains from Stephen’s face.`,
        pt: `Stephen acorda com suor em seu rosto. Ele sonhou com voo. Ele odeia voar. Ele tem 30 anos e nunca esteve em um avião antes. Ele acha que seu medo começou quando ele caiu de uma árvore alta. Felizmente, ele nunca teve razão para voar antes. Mais tarde naquele dia, ele vai trabalhar. Seu chefe o chama para o escritório. Ele está nervoso. Ele tem medo de ter feito algo errado. Ele continua pensando, mas tem certeza de que cumpriu todos os prazos e fez bem. Lentamente, ele abre a porta. O chefe diz-lhe para se sentar. Ele tem esse olhar severo que deixou Stephen mais assustado. Finalmente, seu chefe diz: “Você precisa voar para Los Angeles. Temos um projeto lá que você precisa gerenciar. “A cor some do rosto de Stephen.`,
        en_id: 17
    },
    {
        en: `Jenny is looking for a botany book written by her favorite author, B. Orwell. She already searched the whole section but still does not find it. She sees an old info desk located in a corner, just past the brochure aisle. She approaches it. The man behind the desk immediately asks her, “What can I do for you?” “I am just wondering if you could help me find this book,” she shows the title. The man smiles and says, “Oh, sorry. I have it here with me. I’m just skimming it for a bit.” She takes the book from the man and asks, “Do you like Orwell, too?” “Not much. Do you want to take this home?” “Yes, Mr. —, ” she pauses to read his name from the plate. “Mr. B. Orwell.” Jenny gasps and Mr. Orwell gives her a little smile.`,
        pt: `Jenny está procurando um livro de botânica escrito por seu autor favorito, B. Orwell. Ela já procurou em toda a seção, mas ainda não encontrou. Ela vê um antigo balcão de informações localizado em um canto, logo após o corredor de folhetos. Ela se aproxima. O homem atrás da mesa imediatamente pergunta a ela: “O que posso fazer por você?” “Só estou me perguntando se você poderia me ajudar a encontrar este livro”, ela mostra o título. O homem sorri e diz: “Oh, desculpe. Eu tenho aqui comigo. Estou apenas dando uma olhada nele um pouco.” Ela pega o livro do homem e pergunta: “Você também gosta de Orwell?” "Não muito. Você quer levar isso para casa?” “Sim, Sr. —,” ela faz uma pausa para ler o nome dele no prato. "Senhor. B. Orwell. Jenny suspira e o Sr. Orwell lhe dá um pequeno sorriso.`,
        en_id: 18 
    },
    {
        en: `Natasha is never lucky when she participates in contests. She never wins although she always feels like she will. One day, she told her brother how she was upset about it. He told her she should buy a lottery ticket and choose all of her lucky numbers. This way, maybe she would have better chances to win. Natasha thought it was a good idea. She went to the store and bought one. She picked 10 numbers. She decided to choose, in order, her birthday, her mom’s birthday, her brother’s birthday, her wedding date, the number of dogs she has and her lucky number. The final number was 1228171037. Unfortunately, she didn’t win.`,
        pt: `Natasha nunca tem sorte quando participa de competições. Ela nunca ganha, apesar que ela sempre se sente como ela vai ganhar. Um dia, ela disse ao irmão como ela estava chateada com isso. Ele disse a ela que ela deveria comprar um bilhete de loteria e escolher todos os seus números de sorte. Desta forma, talvez ela teria melhores chances para ganhar. Natasha acha que é uma boa idéia. Ela vai à loja e compra um. Ela tem que escolher 10 números. Ela decide escolher, por ordem, seu aniversário, o aniversário da mãe, o aniversário do irmão, a data do casamento, o número de cães que ela tem e o número da sorte dela. O número final é 1228171037. Infelizmente, ela não ganhou.`,
        en_id: 19
    },
    {
        en: `It’s Christmas today and Ellen is really happy. Her husband bought her a gift and she thinks she knows what it is. She has been wanting some shoes of her favorite designer but these are very pricey. She wasn’t able to afford it by herself, but she thinks it might be the gift her husband got her. When it’s finally time to unwrap the gifts, she is excited. The box has the shape of a shoe box. She unwraps it very quickly. She can’t believe her eyes! It’s the new shoes she wanted. Ellen is very thankful. She gives her husband a big hug and she tells him how much she loves him. She can’t wait to wear her new shoes.`,
        pt: `Hoje é Natal e Ellen está muito feliz. Seu marido comprou-lhe um presente e ela acha que ela sabe o que é. Ela tem desejado alguns sapatos de seu designer favorito, mas estes são muito caros. Ela não era capaz de pagar por isso, mas ela acha que poderia ser o presente que seu marido adquiriu para ela. Quando finalmente é hora de desembrulhar os presentes, ela está animada. A caixa tem a forma de uma caixa de sapato. Ela desenrola-lo muito rapidamente. Ela não pode acreditar em seus olhos! São os sapatos novos que ela queria. Ellen é muito grata. Ela dá um grande abraço ao marido e ela diz o quanto ela o ama. Ela não pode esperar para usar seus sapatos novos.`,
        en_id: 20
    }
    
];

export default allTexts;
